"""Init tables

Revision ID: 1f76da31a250
Revises: 
Create Date: 2025-02-16 06:13:47.218354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f76da31a250'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('int_id', sa.String(length=16), nullable=False),
    sa.Column('str', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('log_address_idx', 'log', ['address'], unique=False, postgresql_using='hash')
    op.create_table('message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('int_id', sa.String(length=16), nullable=False),
    sa.Column('str', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('message_created_idx', 'message', ['created'], unique=False)
    op.create_index('message_int_id_idx', 'message', ['int_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('message_int_id_idx', table_name='message')
    op.drop_index('message_created_idx', table_name='message')
    op.drop_table('message')
    op.drop_index('log_address_idx', table_name='log', postgresql_using='hash')
    op.drop_table('log')
    # ### end Alembic commands ###
